config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :offers do
    resources :reservations, only: %i[new create show]
  end
  resources :reservations, only: %i[index show destroy]

  get 'dashboard', to: 'dashboards#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reservations
  validates :title, :content, :price, :category, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :offers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @user = current_user
    @user_offers = @user.offers
    @user_reservations = @user.reservations
    @reservations_for_user = Reservation.joins(:offer).where(offers: { user_id: @user.id })
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[show edit update destroy]

  def index
    @offers = Offer.all
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR category ILIKE :query"
      @offers = @offers.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def user_offers
    curent_user.offers
  end

  def show
    @reservation = Reservation.new
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(params_offer)
    @offer.user_id = current_user.id
    if @offer.save
      redirect_to dashboard_path, notice: "Offer was successfully created."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @offer.update(params_offer)
    redirect_to @offer, notice: "'Offer was successfully updated"
   else
    render :edit
    end
  end

  def destroy
    @offer.destroy
    redirect_to root_path, notice: 'Offer was successfully destroyed.'
  end

private

def params_offer
  params.require(:offer).permit(:title, :price, :content, :category, :photo)
end

def set_offer
  @offer = Offer.find(params[:id])
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_offer, only: [:new, :create]

  def new
    @reservation = Reservation.new
  end

  def show
    @reservation = Reservation.find(params[:id])
    current_user.reservations
  end

  def create
    @reservation = Reservation.new
    # @reservation = current_user.reservations.build(reservation_params)
    @reservation.date_begin = params[:reservation][:date_begin].split(' to ').first
    @reservation.date_end = params[:reservation][:date_begin].split(' to ').last
    @reservation.offer = @offer
    @reservation.user = current_user
    if @reservation.save
      redirect_to dashboard_path, notice: 'Reservation was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

   def reservation_params
     params.require(:reservation).permit(:date_begin, :date_end)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/dashboard.html.erb
<div class="offers-container">
  <h2 class=title_dashboard>Ma galerie</h2>
  <h1 class=texte_dashboard>Retrouvez ici toutes vos Oeuvres d'arts et réservations</h1>
  <h3 class=texte_dashboard>Oeuvres d'Art ajoutées</h3>
  <div class="test-toto">
    <% @user_offers.each do |offer| %>
      <div class="card">
        <div class="card-img">
          <%= offer.title%><br>
          <% if offer.photo.key %>
            <%= cl_image_tag offer.photo.key, width: 300, height: 220, crop: :fill %>
          <% end %>
        </div>
        <div class="card-content">
          <div><%= offer.title%></div>
          <h5><%= offer.title%></h5>
          <div><%= offer.price%> €/jour</div>
          <div>
            <%= link_to(edit_offer_path(offer)) do %>
              <i class="fa-solid fa-pen-to-square fa-sm" style="color: #b98731;"></i>
            <% end %>
          </div>
          <div class="btn-delete" style="width: 95%;">
            <%= link_to offer_path(id: offer.id), data: {turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr de vouloir supprimer cette offre?' }, class:'btn btn-block' do %>
              <i class="fa-solid fa-trash fa-sm" style="color: #b98731;"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <h3 class=texte_dashboard>Mes réservations d'oeuvres d'art</h3>
  <div class="test-toto">
    <% @user_reservations.each do |reservation| %>
      <div class="card">
        <div class="card-img">
          <div>Du <%= reservation.date_begin%> au <%=reservation.date_end%></div>
          <% if reservation.offer.photo.key %>
            <%= cl_image_tag reservation.offer.photo.key, width: 300, height: 220, crop: :fill %>
          <% end %>
        </div>
        <div class="card-content">
          <%= reservation.offer.title%><br>
          <h5><%= reservation.offer.title%><br></h5>
            <p><%= reservation.offer.price%> €/jour</p>
            <p class="card-text"><%=reservation.offer.content%></p>
        </div>
      </div>
    <% end %>
  </div>


<h3 class="texte_dashboard pb-5">Mes oeuvres d'art qu'on m'a réservées</h3>
  <% if @reservations_for_user.length > 1 %>
    <div class="test-toto">
      <% @reservations_for_user.each do |reservation| %>
        <div class="card">
          <div class="card-img">
            <%= reservation.date_begin%> - <%=reservation.date_begin%>
            <% if reservation.offer.photo.key %>
              <%= cl_image_tag reservation.offer.photo.key, width: 300, height: 220, crop: :fill %>
            <% end %>
          </div>
          <div class="card-content">
            <div><%= reservation.offer.title%></div>
            <h5><%= reservation.offer.title%></h5>
            <div><%= reservation.offer.price%> €/jour</div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtLoc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
      <script>
      AOS.init();
    </script>
    <%= render "shared/navbar" %>
    <div class="container-yield">
    <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for offer, html: {data: {turbo: false}} do |f| %>
<%= f.input :title %>
<%= f.input :category, collection: ["Peintures", "Sculptures", "Livres", "Photographies"] %>
<%= f.input :content %>
<%= f.input :photo, as: :file, input_html: { data: { action: "change->photo-preview#displayPreview", photo_preview_target: "photoInput"} } %>
<%= f.input :price %>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/offers/_header.html.erb
<div class="banner-container banner-change">
  <div class="banner-nav-bar">
  </div>
</div>

app/views/offers/edit.html.erb
<%= render 'header' %>

<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-list">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', offer: @offer %>
      </div>
    </div>
  </div>

</div>

app/views/offers/index.html.erb
<div class="banner">
  <div class="title-container d-flex justify-content-start align-items-center w-75 h-100">
    <div class="ms-5">
      <div class="text-center">
        <h3 class="animate-charcter" data-aos="fade-down"
     data-aos-easing="linear"
     data-aos-duration="1500">Art & Loc</h3>
      </div>
      <div class="toto text-center">
        <h2>
          <span>Art</span>
          <span>éphémère,</span>
          <span> impact</span>
          <span>durable.</span>
          <span> Art</span>
          <span> & </span>
          <span>Loc</span>
          <span> - </span>
          <span>Votre</span>
          <span> galerie,</span>
          <span> votre</span>
          <span> histoire.</span>
        </h2>
</div>

    </div>
  </div>
</div>
</div>
<div class="offers-container" >
<div>
<h1 data-aos="fade-right"
     data-aos-offset="300"
     data-aos-easing="ease-in-sine">Les dernières offres</h1>

<div class="test-toto" data-aos="fade-right"
     data-aos-offset="300"
     data-aos-easing="ease-in-sine">
<% @offers.each_slice(4) do |group| %>
<% group.each do |offer| %>
  <div class="card" >
    <div class="card-img">
    <% if offer.photo.key %>
                <%= cl_image_tag offer.photo.key, width: 300, height: 220, crop: :fill %>
              <% end %>
      <div class="overlay">
        <div class="overlay-content">
          <h5 class="card-title"><%= link_to "View details", offer_path(offer) %></h5>
        </div>
      </div>
      </div>
      <div class="card-content">
        <h2><%= link_to offer.title, offer_path(offer) %></h2>
        <p><%= offer.price%> €/jour</p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/offers/new.html.erb
<%= render 'header' %>

<div data-controller="photo-preview" class="d-flex align-items-center justify-content-center" style="height: 100vh; background: url('https://cdn.pixabay.com/photo/2017/02/15/15/46/abstract-2069084_1280.jpg') center center no-repeat; background-size: cover;">
  <div class="signup-container p-4">
    <div class="white-frame" style="padding: 20px; max-width: 700px; width: 150%;">
      <div class="container">
        <div class="row new-form">
          <div class="col-lg-6 left-bg-list">
            <%= image_tag "", class:"photo-preview", alt: "", data: { photo_preview_target: "img" }  %>
          </div>
          <div class="col-lg-6 right-bg" >
            <%= render 'form', offer: @offer %>
          </div>
        </div>
      </div>
    </div>
  </div>

<%= link_to raw('<i class="fa-solid fa-arrow-left-long" style="color: #9e9e9e;"></i>'), offers_path, style: 'font-size: 48px; position: fixed; bottom: 10px; left: 10px;' %>

</div>

app/views/offers/show.html.erb
<div class="d-flex flex-column align-items-center justify-content-center" style="height: 100vh; background: url('https://cdn.pixabay.com/photo/2017/08/07/11/42/museum-2602957_1280.jpg') center center no-repeat; background-size: cover;">
  <div class="container">
    <div class="row">
      <div class="btn-style">
        <%= link_to offers_path do %>
          <%= link_to raw('<i class="fa-solid fa-arrow-left-long" style="color: #9e9e9e;"></i>'), offers_path, style: 'font-size: 48px; position: fixed; bottom: 10px; left: 10px;' %>
        <% end %>
      </div>
    </div>

    <div class="card mb-3 mx-auto mt-5" style="max-width: 540px; border: 20px solid #2e2e2e;">
      <div class="row g-0">
        <div class="col-md-6">
          <div class="card-body">
            <h2 class="card-title"><strong><%= @offer.title %></strong></h2>
            <h5 class="card-title"><%= @offer.price %>€/jour</h5>
            <div class="card-content" style="margin-right: 20px;">
              <p class="card-text"><%= @offer.content %></p>
              <p class="card-text"><small class="text-body-secondary">Il y a 3 minutes</small></p>
              <%= render 'reservations/partials/form', offer: @offer, reservation: @reservation %>
            </div>
          </div>
        </div>
        <div class="col-md-1 d-flex align-items-center">
          <% if @offer.photo.key %>
            <%= cl_image_tag @offer.photo.key, width: 200, height: 200, crop: :fill %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/dashboard.html.erb
<h1>Mes ventes</h1>

app/views/reservations/dashbord.html.erb
<h1>Mes ventes</h1>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

app/views/reservations/partials/_form.html.erb
<%= simple_form_for([offer, reservation]) do |form| %>

  <%= form.input :date_begin,
        as: :string,
            label: raw("<i class='fa-solid fa-calendar-days fa-xl' style='color: #648dd3;'></i>"),
            input_html: { data: { controller: "datepicker" }, class:"d-none" } %>

  <div class="actions">
    <%= form.submit texte="Louer"%>
  </div>
<% end %>

app/views/reservations/show.html.erb
<h1>Reservation Details</h1>

app/views/shared/_footer.html.erb
<div class="footer-container" >
<div class="langs" >
  <p>France</p>
  <p>|</p>
  <p>Français</p>
  <p>|</p>
  <p>€ (EUR)</p>
  </div>
  <div class="other">
    <p>© 2023 Art & Loc, Inc.</p>
    <a href="#">Conditions d'utilisation</a>
    <a href="#">Confidentialité</a>
    <a href="#">Cookies</a>
    <a href="#">Publicités</a>
    <a href="#">Boutiques locales</a>
    <a href="#">Régions</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid" data-aos="fade-down">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Art (2).png", class: "w-50 ms-3"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="topnav">
      <%= form_with url: offers_path, method: :get, class: "topnav" do %>
      <div class="input-group rounded">
        <%= text_field_tag :query,params[:query],class: "form-control" %>
        <button type="submit" class="input-group-text border-0" id="search-addon">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="align-items-center navbar-nav me-auto">
        <div class="icons">
          <%= link_to "Ajouter une Oeuvre d'art", new_offer_path, class: "new-offer" %>
          <%= link_to "Mes Offres", dashboard_path , class: "new-offer"%>
          <%= link_to "Mes Reservations", dashboard_path, class: "new-offer" %>
        </div>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <%= image_tag "https://ih1.redbubble.net/image.1213539486.1793/raf,360x360,075,t,fafafa:ca443f4786.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Autre action", "#", class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "new-offer" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>